service: bf-ticker

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "sqs:*"
        - "dynamodb:*"
      Resource: "*" 

plugins:
  - serverless-plugin-existing-s3
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
#  ticker:
#    handler: src/handler.ticker
#    events:
#      - schedule: rate(1 minutes)

# Resource declarations should be placed only in mediator project.

