service: bf-mediator

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "sqs:*"
        - "dynamodb:*"
      Resource: "*" 

plugins:
  - serverless-plugin-existing-s3
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get

resources:
  Resources:
    taskQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${env:TASK_QUEUE}
